source lib/library.exp


proc unit_exit {} {
    # Exit bash
    send "\rexit\r"
}


proc unit_start {} {
    start_bash
    assert_bash_exec {source "../upvar.sh"}
    init_tcl_bash_globals

    global OPT_BASH_XTRACE
    if {[info exists OPT_BASH_XTRACE]} {
        init_bash_xtrace
    }
    global OPT_TIMEOUT
    if {[info exists OPT_TIMEOUT]} {
        global timeout
        verbose "Changing default expect timeout from $timeout to $OPT_TIMEOUT"
        set timeout $OPT_TIMEOUT
    }
}


proc unit_version {} {
    puts "$::TESTDIR, bash-$::BASH_VERSION"
}
