proc setup {} {
    assert_bash_exec {source lib/upvars.sh}
    save_env
}; # setup()


proc teardown {} {
    assert_bash_exec {unset -v b; unset -f f g}
    assert_env_unmodified 
}; # teardown()


setup


set test "runs without errors"
assert_bash_exec {upvars --version > /dev/null} $test


sync_after_int


set test "returns value local"
set cmd {\
    unset -v a;\
    f() { local "$1" && upvars -v $1 B; };\
    g() { local a; f a; echo $a; };\
    g\
}
assert_bash_list B $cmd $test

set test "global is unmodified"
assert_bash_list {} {printf %s $a} $test


sync_after_int


set test "returns array local"
set cmd {\
    unset -v a;\
    f() { local r=(e1 e2 "e3  e4" $'e5\ne6'); local "$1" && upvars -a${#r[@]} $1 "${r[@]}"; };\
    g() { local a; f a; echo "${a[@]}"; };\
    g\
}
assert_bash_list {e1 e2 {e3  e4} "e5\ne6"} $cmd $test


sync_after_int


set test "no conflict"
set cmd {\
    unset -v a b;\
    g() { local a=A b=B; local "$1" "$2" && upvars -v $1 $a -v $2 $b; };\
    f() { local b a; g b a; printf $'%s\n' "$b $a"; };\
    f\
}
assert_bash_list {A B} $cmd $test


set test "return empty array"
set cmd {\
    unset -v a;\
    g() { local a=(); local "$1" && upvars -a${#a[@]} a "${a[@]}"; };\
    f() { local a; g a; declare -p a; };\
    f\
}
assert_bash_list {{declare -a a='()'}} $cmd $test

    
set test "error when N in -aN not specified"
set cmd {upvars -a b c; printf %s $?}
send "$cmd\r"
expect -ex "$cmd\r\n"
expect {
    -re "^bash: upvars: `-a': missing number specifier\r\n1/@" {pass $test}
}


sync_after_int


set test "error when invalid N in -aN specified"
set cmd {upvars -aA b c; printf %s $?}
send "$cmd\r"
expect -ex "$cmd\r\n"
expect {
    -re "^bash: upvars: `-aA': invalid number specifier\r\n1/@" {pass $test}
}


sync_after_int


set test "error when -a1 has missing argument"
set cmd {upvars -a1 b; printf %s $?}
send "$cmd\r"
expect -ex "$cmd\r\n"
expect {
    #-re "^bash: upvars: `-a1 b': missing argument\(s\)\r\n1/@$" {pass $test}
    -re "^bash: upvars: `-a1 b': missing argument\\(s\\)\r\n1/@$" {pass $test}
}


sync_after_int


set test "error when -a0 has wrong argument count"
set cmd {upvars -a0; printf %s $?}
send "$cmd\r"
expect -ex "$cmd\r\n"
expect {
    -re "^bash: upvars: `-a0': missing argument\\(s\\)\r\n1/@" {pass $test}
}


sync_after_int


set test "show usage when no arguments"
set cmd {upvars; printf %s $?}
send "$cmd\r"
expect -ex "$cmd\r\n"
expect {
    -re "^upvars: usage: upvars \\\[-v varname value\\\] |\
        \\\[-aN varname \\\[value ...\\\]\\\] ...\r\n1/@" {pass $test}
}


sync_after_int


set test "return optional value"
set cmd {\
    unset -v a;\
    g() { local a=foo; [[ "$1" ]] && local "$1" && upvars -v $1 "$a"; };\
    f() { local a; g; declare -p a; };\
    f\
}
assert_bash_list {{declare -- a=""}} $cmd $test


sync_after_int


set test "return none of two optional values"
set cmd {\
    f() { return_two_optional_values; };\
    f\
}
assert_bash_list "" $cmd $test


sync_after_int


set test "return one of two optional values"
set cmd {\
    unset -v a;\
    f() { local a; return_two_optional_values a; declare -p a; };\
    f\
}
assert_bash_list {{declare -- a="foo"}} $cmd $test


sync_after_int


set test "return two of two optional values"
set cmd {\
    unset -v a b;\
    f() { local a b; return_two_optional_values a b; declare -p a b; };\
    f\
}
assert_bash_list {{declare -- a="foo"} {declare -- b="bar"}} $cmd $test


sync_after_int


set test "return none of two optional arrays"
set cmd {\
    f() { return_two_optional_arrays; };\
    f\
}
assert_bash_list "" $cmd $test


sync_after_int


set test "return one of two optional arrays"
set cmd {\
    unset -v a;\
    f() { local a; return_two_optional_arrays a; declare -p a; };\
    f\
}
assert_bash_list {{declare -a a='([0]="foo" [1]="bar")'}} $cmd $test


sync_after_int


set test "return two of two optional arrays"
set cmd {\
    unset -v a b;\
    f() { local a b; return_two_optional_arrays a b; declare -p a b; };\
    f\
}
assert_bash_list {
    {declare -a a='([0]="foo" [1]="bar")'}
    {declare -a b='([0]="cee" [1]="dee")'}
} $cmd $test


sync_after_int


teardown
